apiVersion: v1
kind: Pod
metadata:
  name: init
spec:
  initContainers:
  - name: init-mydb
    image: busybox
    command: [ "sh", "-c", "until nslookup mydb; do echo waiting for mydb; sleep 2; done" ]
  - name: install
    image: busybo
    command: [ "sh", "-c", "echo Hello from the init container > /work-dir/index.html" ]
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}
