apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: demo-dep
  name: nginx
spec:
  selector:
    matchLabels:
      demo: deployment
  replicas: 3
  template:
    metadata:
      labels:
        demo: deployment
        version: v1.7.9
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
