apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: demo-ds
  name: daemons
spec:
  template:
    metadata:
      labels:
        demo: daemons
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:v0.13.0
