apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: demo-ds
  name: red
spec:
  template:
    metadata:
      labels:
        demo: red
    spec:
      nodeSelector:
        color: red
      containers:
      - name: hostname
        image: gcr.io/google_containers/serve_hostname:1.1
