apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: demo-ds
  name: red
spec:
  template:
    metadata:
      labels:
        demo: red
    spec:
      nodeSelector:
        color: red
      containers:
      - name: node-exporter
        image: prom/node-exporter:v0.14.0
